resolution: [1280, 720]
resolution_d: [1280, 720]
fps: 30
dictionary: DICT_4X4_50
marker_length: 0.04750  # default marker length
marker_sizes:
  25: 0.0480        # marker 25 has a size of 0.08 m
  33: 0.0330        # marker 23 has a size of 0.06 m
  0: 0.0470
  10: 0.0470
origin_id: 0
offset_x: -0.165
offset_y: -0.165
offset_z: 0.03
bias_x: -0.01
bias_y: -0.0085
bias_z: -0.015
