resolution: [1280, 720]
resolution_d: [1280, 720]
fps: 30
dictionary: DICT_4X4_50
marker_length: 0.04750  # default marker length
marker_sizes:
  25: 0.0480        # marker 25 has a size of 0.08 m
  33: 0.0330        # marker 23 has a size of 0.06 m
  0: 0.0700
  10: 0.0470
origin_id: 0
offset_x: -0.091
offset_y: -0.091
offset_z: -0.013
bias_x: 0.0000
bias_y: 0.0000
bias_z: 0.0000

# Hand detection bias parameters
hand_bias_x: 0.0000  # Forward/backward adjustment
hand_bias_y: 0.0000  # Left/right adjustment
hand_bias_z: 0.0000  # Up/down adjustment
