from .sleepstate import sleepstate
from .rest import rest
from .close_iron import close_iron
from .cup_to_iron import cup_to_iron
from .empty_cup import empty_cup
from .error import error
from .put_down_spray import put_down_spray
from .fill_cup import fill_cup
from .fun_time import fun_time
from .home import home
from .open_iron import open_iron
from .open_iron2 import open_iron2
from .pick_up_spray import pick_up_spray
from .pick_up_waffle import pick_up_waffle
from .place_cup_to_stat import place_cup_to_stat
from .return_cup import return_cup
from .return_stick import return_stick
from .serve_waffle import serve_waffle
from .spray import spray